###
# Swiftlint configuration file.
# Latest version supported: 0.47.1
# Any newer version hasn't been checked yet and might not follow the style guide.
#
# To update your local version of this file, execute the following command line:
# curl https://raw.githubusercontent.com/kevindelord/swift-style-guide/master/.swiftlint.yml > .swiftlint.yml
###

# Rule identifiers to exclude from running
disabled_rules:
    - comment_spacing
    - inclusive_language
    - orphaned_doc_comment
    - todo

# paths to ignore during linting. overridden by `included`.
excluded:
    - Carthage
    - Pods
    - fastlane

# rule parameters
comma:
    severity: error
    
colon:
    severity: error

control_statement:
    severity: error

closing_brace:
    severity: error

closure_end_indentation:
    severity: error
    
collection_alignment:
    severity: error

convenience_type:
    severity: error

cyclomatic_complexity:
    error: 10

discouraged_assert:
    severity: error

discouraged_object_literal:
    severity: error

discouraged_optional_boolean:
    severity: error

empty_enum_arguments:
    severity: error
    
empty_parentheses_with_trailing_closure:
    severity: error
    
file_length:
    error: 400

first_where:
    severity: error
    
force_unwrapping:
    severity: error

function_body_length:
    error: 40

function_parameter_count:
    error: 5
    
implicit_getter:
    severity: error

identifier_name:
    severity: error
    
large_tuple:
    severity: error

last_where:
    severity: error

line_length:
    error: 120
    
mark:
    severity: error
    
multiple_closures_with_trailing_closure:
    severity: error
    
no_space_in_method_call:
    severity: error

opening_brace:
    severity: error

prefer_self_in_static_references:
    severity: error
    
prefer_zero_over_explicit_init:
    severity: error

private_outlet:
    allow_private_set: true
    severity: error

private_over_fileprivate:
    severity: error
    
redundant_discardable_let:
    severity: error
    
redundant_optional_initialization:
    severity: error
     
return_arrow_whitespace:
    severity: error

sorted_first_last:
    severity: error

statement_position:
    severity: error
    
superfluous_disable_command:
    severity: error

switch_case_alignment:
    severity: error

toggle_bool:
    severity: error

trailing_newline:
    severity: error

trailing_semicolon:
    severity: error

type_body_length:
    error: 200

type_name:
    severity: error
    
unneeded_break_in_switch:
    severity: error

unused_closure_parameter:
    severity: error
    
unused_optional_binding:
    severity: error

unused_declaration:
    severity: error

unused_import:
    severity: error

vertical_parameter_alignment:
    severity: error

vertical_whitespace:
    severity: error

weak_delegate:
    severity: error

# reporter
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)

# custom rules
custom_rules:
    boolean_operators_end_of_line:
        name: "Boolean Operators"
        regex: '((?:&&|\|\|)$)'
        message: "Boolean operators should not be at the end of line"
        severity: error
        
    mark_style:
        name: "MARK Style"
        regex: '(//?[ ]MARK: -?[a-zA-Z0-9])'
        message: "Marks should follow the following structure: // MARK: - Section"
        severity: error

# added rules that are not enabled by default
opt_in_rules:
    - attributes
    - closure_end_indentation
    - closure_spacing
    - closing_brace
    - collection_alignment
    - convenience_type
    - discouraged_assert
    - discouraged_object_literal
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - explicit_init
    - first_where
    - force_unwrapping
    - implicit_getter
    - last_where
    - nimble_operator
    - no_space_in_method_call
    - prefer_self_in_static_references
    - prefer_zero_over_explicit_init
    - private_outlet
    - private_over_fileprivate
    - redundant_nil_coalescing
    - sorted_first_last
    - toggle_bool
    - unneeded_parentheses_in_closure_argument
    - unused_declaration
    - unused_import
    - vertical_parameter_alignment
    - vertical_whitespace
    - weak_delegate
